version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=nithin
      - DB_PASSWORD=nithin
      - JWT_SECRET=hey-there
    volumes:
      - .:/usr/src/app
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nithin
      MYSQL_DATABASE: feedbackdb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  db_data:
