services:
  - type: web
    name: feedback-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: nithin
      - key: DB_NAME
        value: feedbackdb
      - key: JWT_SECRET
        value: hey-there
